// This file is auto-generated by @hey-api/openapi-ts

export const $TranslationJobModel = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            nullable: true
        },
        customerName: {
            type: 'string',
            nullable: true
        },
        status: {
            type: 'string',
            nullable: true
        },
        originalContent: {
            type: 'string',
            nullable: true
        },
        translatedContent: {
            type: 'string',
            nullable: true
        },
        price: {
            type: 'number',
            format: 'double'
        }
    },
    additionalProperties: false
} as const;

export const $JobStatus = {
    enum: [0, 1, 2, 3],
    type: 'integer',
    format: 'int32'
} as const;

export const $TranslatorModel = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            nullable: true
        },
        name: {
            type: 'string',
            nullable: true
        },
        hourlyRate: {
            type: 'string',
            nullable: true
        },
        status: {
            type: 'string',
            nullable: true
        },
        creditCardNumber: {
            type: 'string',
            nullable: true
        }
    },
    additionalProperties: false
} as const;

export const $TranslatorStatus = {
    enum: [0, 1, 2, 3],
    type: 'integer',
    format: 'int32'
} as const;